import pygame
keymap={
    "up arrow":pygame.K_UP,
    "down arrow":pygame.K_DOWN,
    "left arrow":pygame.K_LEFT,
    "right arrow":pygame.K_RIGHT,
    "space":pygame.K_SPACE,
    "enter":pygame.K_RETURN,
    "escape":pygame.K_ESCAPE,
    "a":pygame.K_a,
    "b":pygame.K_b,
    "c":pygame.K_c,
    "d":pygame.K_d,
    "e":pygame.K_e,
    "f":pygame.K_f,
    "g":pygame.K_g,
    "h":pygame.K_h,
    "i":pygame.K_i,
    "j":pygame.K_j,
    "k":pygame.K_k,
    "l":pygame.K_l,
    "m":pygame.K_m,
    "n":pygame.K_n,
    "o":pygame.K_o,
    "p":pygame.K_p,
    "q":pygame.K_q,
    "r":pygame.K_r,
    "s":pygame.K_s,
    "t":pygame.K_t,
    "u":pygame.K_u,
    "v":pygame.K_v,
    "w":pygame.K_w,
    "x":pygame.K_x,
    "y":pygame.K_y,
    "z":pygame.K_z,
    "1":pygame.K_1,
    "2":pygame.K_2,
    "3":pygame.K_3,
    "4":pygame.K_4,
    "5":pygame.K_5,
    "6":pygame.K_6,
    "7":pygame.K_7,
    "8":pygame.K_8,
    "9":pygame.K_9,
    "0":pygame.K_0,
    "numpad 0":pygame.K_KP0,
    "numpad 1":pygame.K_KP1,
    "numpad 2":pygame.K_KP2,
    "numpad 3":pygame.K_KP3,
    "numpad 4":pygame.K_KP4,
    "numpad 5":pygame.K_KP5,
    "numpad 6":pygame.K_KP6,
    "numpad 7":pygame.K_KP7,
    "numpad 8":pygame.K_KP8,
    "numpad 9":pygame.K_KP9,
    "numpad *":pygame.K_KP_MULTIPLY,
    "numpad +":pygame.K_KP_PLUS,
    "numpad -":pygame.K_KP_MINUS,
    "numpad .":pygame.K_KP_PERIOD,
    "numpad /":pygame.K_KP_DIVIDE,
    "numpad enter":pygame.K_KP_ENTER,
    "comma":pygame.K_COMMA,
}
#AI写的
